// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscribeReq.proto

package org.example.nettylearning.demo8;

public final class SubscribeReqProto {
  private SubscribeReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubscribeReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SubscribeReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 subReqID = 1;</code>
     */
    java.util.List<Integer> getSubReqIDList();
    /**
     * <code>repeated int32 subReqID = 1;</code>
     */
    int getSubReqIDCount();
    /**
     * <code>repeated int32 subReqID = 1;</code>
     */
    int getSubReqID(int index);

    /**
     * <code>repeated string userName = 2;</code>
     */
    java.util.List<String>
        getUserNameList();
    /**
     * <code>repeated string userName = 2;</code>
     */
    int getUserNameCount();
    /**
     * <code>repeated string userName = 2;</code>
     */
    String getUserName(int index);
    /**
     * <code>repeated string userName = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes(int index);

    /**
     * <code>repeated string productName = 3;</code>
     */
    java.util.List<String>
        getProductNameList();
    /**
     * <code>repeated string productName = 3;</code>
     */
    int getProductNameCount();
    /**
     * <code>repeated string productName = 3;</code>
     */
    String getProductName(int index);
    /**
     * <code>repeated string productName = 3;</code>
     */
    com.google.protobuf.ByteString
        getProductNameBytes(int index);

    /**
     * <code>repeated string address = 4;</code>
     */
    java.util.List<String>
        getAddressList();
    /**
     * <code>repeated string address = 4;</code>
     */
    int getAddressCount();
    /**
     * <code>repeated string address = 4;</code>
     */
    String getAddress(int index);
    /**
     * <code>repeated string address = 4;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes(int index);
  }
  /**
   * Protobuf type {@code SubscribeReq}
   */
  public  static final class SubscribeReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SubscribeReq)
      SubscribeReqOrBuilder {
    // Use SubscribeReq.newBuilder() to construct.
    private SubscribeReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubscribeReq() {
      subReqID_ = java.util.Collections.emptyList();
      userName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      productName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SubscribeReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                subReqID_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              subReqID_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                subReqID_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                subReqID_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                userName_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              userName_.add(s);
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                productName_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              productName_.add(s);
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                address_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              address_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          subReqID_ = java.util.Collections.unmodifiableList(subReqID_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          userName_ = userName_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          productName_ = productName_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          address_ = address_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SubscribeReqProto.internal_static_SubscribeReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SubscribeReqProto.internal_static_SubscribeReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SubscribeReqProto.SubscribeReq.class, SubscribeReqProto.SubscribeReq.Builder.class);
    }

    public static final int SUBREQID_FIELD_NUMBER = 1;
    private java.util.List<Integer> subReqID_;
    /**
     * <code>repeated int32 subReqID = 1;</code>
     */
    public java.util.List<Integer>
        getSubReqIDList() {
      return subReqID_;
    }
    /**
     * <code>repeated int32 subReqID = 1;</code>
     */
    public int getSubReqIDCount() {
      return subReqID_.size();
    }
    /**
     * <code>repeated int32 subReqID = 1;</code>
     */
    public int getSubReqID(int index) {
      return subReqID_.get(index);
    }
    private int subReqIDMemoizedSerializedSize = -1;

    public static final int USERNAME_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList userName_;
    /**
     * <code>repeated string userName = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getUserNameList() {
      return userName_;
    }
    /**
     * <code>repeated string userName = 2;</code>
     */
    public int getUserNameCount() {
      return userName_.size();
    }
    /**
     * <code>repeated string userName = 2;</code>
     */
    public String getUserName(int index) {
      return userName_.get(index);
    }
    /**
     * <code>repeated string userName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes(int index) {
      return userName_.getByteString(index);
    }

    public static final int PRODUCTNAME_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList productName_;
    /**
     * <code>repeated string productName = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getProductNameList() {
      return productName_;
    }
    /**
     * <code>repeated string productName = 3;</code>
     */
    public int getProductNameCount() {
      return productName_.size();
    }
    /**
     * <code>repeated string productName = 3;</code>
     */
    public String getProductName(int index) {
      return productName_.get(index);
    }
    /**
     * <code>repeated string productName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProductNameBytes(int index) {
      return productName_.getByteString(index);
    }

    public static final int ADDRESS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList address_;
    /**
     * <code>repeated string address = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAddressList() {
      return address_;
    }
    /**
     * <code>repeated string address = 4;</code>
     */
    public int getAddressCount() {
      return address_.size();
    }
    /**
     * <code>repeated string address = 4;</code>
     */
    public String getAddress(int index) {
      return address_.get(index);
    }
    /**
     * <code>repeated string address = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes(int index) {
      return address_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getSubReqIDList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(subReqIDMemoizedSerializedSize);
      }
      for (int i = 0; i < subReqID_.size(); i++) {
        output.writeInt32NoTag(subReqID_.get(i));
      }
      for (int i = 0; i < userName_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_.getRaw(i));
      }
      for (int i = 0; i < productName_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, productName_.getRaw(i));
      }
      for (int i = 0; i < address_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, address_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < subReqID_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(subReqID_.get(i));
        }
        size += dataSize;
        if (!getSubReqIDList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        subReqIDMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < userName_.size(); i++) {
          dataSize += computeStringSizeNoTag(userName_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getUserNameList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < productName_.size(); i++) {
          dataSize += computeStringSizeNoTag(productName_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getProductNameList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < address_.size(); i++) {
          dataSize += computeStringSizeNoTag(address_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAddressList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SubscribeReqProto.SubscribeReq)) {
        return super.equals(obj);
      }
      SubscribeReqProto.SubscribeReq other = (SubscribeReqProto.SubscribeReq) obj;

      boolean result = true;
      result = result && getSubReqIDList()
          .equals(other.getSubReqIDList());
      result = result && getUserNameList()
          .equals(other.getUserNameList());
      result = result && getProductNameList()
          .equals(other.getProductNameList());
      result = result && getAddressList()
          .equals(other.getAddressList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getSubReqIDCount() > 0) {
        hash = (37 * hash) + SUBREQID_FIELD_NUMBER;
        hash = (53 * hash) + getSubReqIDList().hashCode();
      }
      if (getUserNameCount() > 0) {
        hash = (37 * hash) + USERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getUserNameList().hashCode();
      }
      if (getProductNameCount() > 0) {
        hash = (37 * hash) + PRODUCTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getProductNameList().hashCode();
      }
      if (getAddressCount() > 0) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddressList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SubscribeReqProto.SubscribeReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SubscribeReqProto.SubscribeReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SubscribeReqProto.SubscribeReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SubscribeReqProto.SubscribeReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SubscribeReqProto.SubscribeReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SubscribeReqProto.SubscribeReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SubscribeReqProto.SubscribeReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SubscribeReqProto.SubscribeReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SubscribeReqProto.SubscribeReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SubscribeReqProto.SubscribeReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SubscribeReqProto.SubscribeReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SubscribeReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SubscribeReq)
        SubscribeReqProto.SubscribeReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SubscribeReqProto.internal_static_SubscribeReq_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SubscribeReqProto.internal_static_SubscribeReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SubscribeReqProto.SubscribeReq.class, SubscribeReqProto.SubscribeReq.Builder.class);
      }

      // Construct using org.example.netty.learning.demo8.SubscribeReqProto.SubscribeReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        subReqID_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        productName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SubscribeReqProto.internal_static_SubscribeReq_descriptor;
      }

      public SubscribeReqProto.SubscribeReq getDefaultInstanceForType() {
        return SubscribeReqProto.SubscribeReq.getDefaultInstance();
      }

      public SubscribeReqProto.SubscribeReq build() {
        SubscribeReqProto.SubscribeReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SubscribeReqProto.SubscribeReq buildPartial() {
        SubscribeReqProto.SubscribeReq result = new SubscribeReqProto.SubscribeReq(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          subReqID_ = java.util.Collections.unmodifiableList(subReqID_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.subReqID_ = subReqID_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          userName_ = userName_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.userName_ = userName_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          productName_ = productName_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.productName_ = productName_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          address_ = address_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.address_ = address_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SubscribeReqProto.SubscribeReq) {
          return mergeFrom((SubscribeReqProto.SubscribeReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SubscribeReqProto.SubscribeReq other) {
        if (other == SubscribeReqProto.SubscribeReq.getDefaultInstance()) return this;
        if (!other.subReqID_.isEmpty()) {
          if (subReqID_.isEmpty()) {
            subReqID_ = other.subReqID_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSubReqIDIsMutable();
            subReqID_.addAll(other.subReqID_);
          }
          onChanged();
        }
        if (!other.userName_.isEmpty()) {
          if (userName_.isEmpty()) {
            userName_ = other.userName_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureUserNameIsMutable();
            userName_.addAll(other.userName_);
          }
          onChanged();
        }
        if (!other.productName_.isEmpty()) {
          if (productName_.isEmpty()) {
            productName_ = other.productName_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureProductNameIsMutable();
            productName_.addAll(other.productName_);
          }
          onChanged();
        }
        if (!other.address_.isEmpty()) {
          if (address_.isEmpty()) {
            address_ = other.address_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureAddressIsMutable();
            address_.addAll(other.address_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SubscribeReqProto.SubscribeReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SubscribeReqProto.SubscribeReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Integer> subReqID_ = java.util.Collections.emptyList();
      private void ensureSubReqIDIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          subReqID_ = new java.util.ArrayList<Integer>(subReqID_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 subReqID = 1;</code>
       */
      public java.util.List<Integer>
          getSubReqIDList() {
        return java.util.Collections.unmodifiableList(subReqID_);
      }
      /**
       * <code>repeated int32 subReqID = 1;</code>
       */
      public int getSubReqIDCount() {
        return subReqID_.size();
      }
      /**
       * <code>repeated int32 subReqID = 1;</code>
       */
      public int getSubReqID(int index) {
        return subReqID_.get(index);
      }
      /**
       * <code>repeated int32 subReqID = 1;</code>
       */
      public Builder setSubReqID(
          int index, int value) {
        ensureSubReqIDIsMutable();
        subReqID_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 subReqID = 1;</code>
       */
      public Builder addSubReqID(int value) {
        ensureSubReqIDIsMutable();
        subReqID_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 subReqID = 1;</code>
       */
      public Builder addAllSubReqID(
          Iterable<? extends Integer> values) {
        ensureSubReqIDIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, subReqID_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 subReqID = 1;</code>
       */
      public Builder clearSubReqID() {
        subReqID_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList userName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureUserNameIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          userName_ = new com.google.protobuf.LazyStringArrayList(userName_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string userName = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getUserNameList() {
        return userName_.getUnmodifiableView();
      }
      /**
       * <code>repeated string userName = 2;</code>
       */
      public int getUserNameCount() {
        return userName_.size();
      }
      /**
       * <code>repeated string userName = 2;</code>
       */
      public String getUserName(int index) {
        return userName_.get(index);
      }
      /**
       * <code>repeated string userName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes(int index) {
        return userName_.getByteString(index);
      }
      /**
       * <code>repeated string userName = 2;</code>
       */
      public Builder setUserName(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUserNameIsMutable();
        userName_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userName = 2;</code>
       */
      public Builder addUserName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUserNameIsMutable();
        userName_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userName = 2;</code>
       */
      public Builder addAllUserName(
          Iterable<String> values) {
        ensureUserNameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, userName_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userName = 2;</code>
       */
      public Builder clearUserName() {
        userName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userName = 2;</code>
       */
      public Builder addUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureUserNameIsMutable();
        userName_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList productName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureProductNameIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          productName_ = new com.google.protobuf.LazyStringArrayList(productName_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string productName = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getProductNameList() {
        return productName_.getUnmodifiableView();
      }
      /**
       * <code>repeated string productName = 3;</code>
       */
      public int getProductNameCount() {
        return productName_.size();
      }
      /**
       * <code>repeated string productName = 3;</code>
       */
      public String getProductName(int index) {
        return productName_.get(index);
      }
      /**
       * <code>repeated string productName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getProductNameBytes(int index) {
        return productName_.getByteString(index);
      }
      /**
       * <code>repeated string productName = 3;</code>
       */
      public Builder setProductName(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProductNameIsMutable();
        productName_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string productName = 3;</code>
       */
      public Builder addProductName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProductNameIsMutable();
        productName_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string productName = 3;</code>
       */
      public Builder addAllProductName(
          Iterable<String> values) {
        ensureProductNameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, productName_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string productName = 3;</code>
       */
      public Builder clearProductName() {
        productName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string productName = 3;</code>
       */
      public Builder addProductNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureProductNameIsMutable();
        productName_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAddressIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          address_ = new com.google.protobuf.LazyStringArrayList(address_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string address = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getAddressList() {
        return address_.getUnmodifiableView();
      }
      /**
       * <code>repeated string address = 4;</code>
       */
      public int getAddressCount() {
        return address_.size();
      }
      /**
       * <code>repeated string address = 4;</code>
       */
      public String getAddress(int index) {
        return address_.get(index);
      }
      /**
       * <code>repeated string address = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes(int index) {
        return address_.getByteString(index);
      }
      /**
       * <code>repeated string address = 4;</code>
       */
      public Builder setAddress(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressIsMutable();
        address_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string address = 4;</code>
       */
      public Builder addAddress(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressIsMutable();
        address_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string address = 4;</code>
       */
      public Builder addAllAddress(
          Iterable<String> values) {
        ensureAddressIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, address_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string address = 4;</code>
       */
      public Builder clearAddress() {
        address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string address = 4;</code>
       */
      public Builder addAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureAddressIsMutable();
        address_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SubscribeReq)
    }

    // @@protoc_insertion_point(class_scope:SubscribeReq)
    private static final SubscribeReqProto.SubscribeReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SubscribeReqProto.SubscribeReq();
    }

    public static SubscribeReqProto.SubscribeReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubscribeReq>
        PARSER = new com.google.protobuf.AbstractParser<SubscribeReq>() {
      public SubscribeReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SubscribeReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SubscribeReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SubscribeReq> getParserForType() {
      return PARSER;
    }

    public SubscribeReqProto.SubscribeReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubscribeReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubscribeReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022SubscribeReq.proto\"X\n\014SubscribeReq\022\020\n\010" +
      "subReqID\030\001 \003(\005\022\020\n\010userName\030\002 \003(\t\022\023\n\013prod" +
      "uctName\030\003 \003(\t\022\017\n\007address\030\004 \003(\tB5\n org.ex" +
      "ample.netty.learning.demo8B\021SubscribeReq" +
      "Protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SubscribeReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SubscribeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubscribeReq_descriptor,
        new String[] { "SubReqID", "UserName", "ProductName", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
